# Generated by Django 4.0 on 2021-12-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzamart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
