# Generated by Django 4.0 on 2021-12-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzamart', '0002_delete_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=200)),
                ('inStock', models.BooleanField()),
                ('allergyTags', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
