# Generated by Django 4.0 on 2021-12-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzamart', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'Pizza'},
        ),
    ]
