# Generated by Django 4.0 on 2021-12-28 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pizzamart', '0004_alter_pizza_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orders', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('preparing', models.BooleanField()),
                ('delivering', models.BooleanField()),
                ('received', models.BooleanField()),
            ],
        ),
    ]
